import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "canvas-cream": "#F3F0EE",
        "ink-black": "#141413",
        "light-signal-orange": "#F37338",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "surface": "#F3F0EE",
        "surface-container-low": "#f5f3f3",
        "surface-container-high": "#e9e8e7",
        "on-tertiary-container": "#d85f25",
        "surface-dim": "#dbdad9",
        "outline": "#767872",
        "on-primary-fixed-variant": "#474745",
        "background": "#F3F0EE",
        "secondary": "#5f5e5d",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "inverse-primary": "#c9c6c4",
        "surface-container": "#efeded",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#474745",
        "primary-fixed": "#e5e2e0",
        "error-container": "#ffdad6",
        "surface-bright": "#fbf9f8",
        "inverse-surface": "#303031",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#1c1c1a",
        "surface-variant": "#e4e2e2",
        "on-tertiary-fixed-variant": "#7e2c00",
        "white": "#FFFFFF",
        "lifted-cream": "#FCFBFA",
        "secondary-fixed": "#e5e2e0",
        "primary-fixed-dim": "#c9c6c4",
        "primary": "#000000",
        "tertiary-fixed": "#ffdbcd",
        "signal-orange": "#CF4500",
        "secondary-container": "#e2dfdd",
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "link-blue": "#3860BE",
        "surface-tint": "#5f5e5d",
        "on-primary-container": "#858382",
        "on-primary-fixed": "#1c1c1a",
        "secondary-fixed-dim": "#c8c6c4",
        "outline-variant": "#c7c7c0",
        "on-surface-variant": "#464742",
        "dust-taupe": "#D1CDC7",
        "on-tertiary-fixed": "#360f00",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1c1c1b",
        "tertiary-fixed-dim": "#ffb598",
        "tertiary-container": "#360f00",
        "surface-container-highest": "#e4e2e2",
        "on-secondary-container": "#636261",
        "success": "#22C55E",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-v-desktop": "128px",
        "card-padding": "32px",
        "nav-offset": "24px",
        "section-v-mobile": "48px",
        "gutter": "48px",
        "base": "8px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "footer-link": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "eyebrow": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["64px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "footer-link": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "450" }],
        "headline-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "eyebrow": ["14px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "28.8px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "22.4px", letterSpacing: "0em", fontWeight: "450" }],
        "label-md": ["16px", { lineHeight: "16px", letterSpacing: "-0.03em", fontWeight: "500" }],
      },
      boxShadow: {
        "nav": "0 4px 24px rgba(0,0,0,0.04)",
        "card": "0 8px 48px rgba(0,0,0,0.04)",
        "card-hover": "0 16px 64px rgba(0,0,0,0.08)",
        "bottom-nav": "0 -4px 32px rgba(0,0,0,0.06)",
        "lifted": "0 2px 16px rgba(0,0,0,0.03)",
      },
      animation: {
        "ticker": "ticker 25s linear infinite",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(-100%)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
